### PR TITLE
Polyglot

### PR DESCRIPTION
**Pull request by gilgongo**
Just checking how it works via the CLI (needed to create an access token)

### CODE REVIEW

**Comment by ann0see** [comment]
I'm not yet sure but if we merge this, will the changes done on the master branch after the split off be reverted? I don't think so.

**Comment by gilgongo** [comment]
Yes, I was a bit confused about this. My first test edit I did was in the web UI and I just committed straight to the polyglot branch without a pull request. This time I did it via git on the CLUI and it seemed to want me to do a pull request after that. Hm.

**Comment by ann0see** [comment]
> This time I did it via git on the CLUI and it seemed to want me to do a pull request after that. Hm.

Probably I was working and pushed my changes while you edited the code on your machine.

I'd suggest to make polyglot the default branch (in github) and rename the main branch to "old-plugin"

**Comment by gilgongo** [comment]
OK I've made polyglot now the default branch. Not sure how I change the name of main though but I'll keep looking.

**Comment by ann0see** [comment]
For me it seems as if it's only possible to delete and recreate it: https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/

**Pull request closed without merging**
